# Generated by Django 3.0.3 on 2020-04-25 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('sum_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cus_fname', models.CharField(max_length=30)),
                ('cus_lname', models.CharField(max_length=30)),
                ('cus_address', models.TextField()),
                ('cus_img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.TextField()),
                ('shop_desc', models.CharField(max_length=400)),
                ('shop_icon', models.ImageField(upload_to='icon')),
                ('shop_bg', models.ImageField(upload_to='bg')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='market.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0)),
                ('prod_desc', models.TextField()),
                ('img', models.ImageField(default='noimg.jpg', upload_to='product')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='market.SubCategory')),
                ('shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.ShopOwner')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment', models.CharField(choices=[('01', 'iBank Pay'), ('02', 'Youeself')], default='01', max_length=2)),
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('item_price', models.FloatField(default=0)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Customer'),
        ),
    ]
