# Generated by Django 3.0.3 on 2020-04-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200427_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='market.Cart'),
        ),
    ]
